version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: "mix phx.server"
    volumes:
      - ./:/home
    ports:
      - "4000:4000"
    depends_on:
      - db
